version: "3.9"
services:
  shapes-service:
    build:
      context: service/shapes-service
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - "8093:8093"
    volumes:
      - ./shapes:/app/shapes
  # shapes:
  #   build:
  #     context: shapes
  #     dockerfile: Dockerfile
  #   platform: linux/x86_64
